#Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: springboot-demo
---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: springboot-demo
  name: springboot-demo
  labels:
    app: springboot-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-demo
  template:
    metadata:
      labels:
        app: springboot-demo
    spec:
      containers:
        - name: springboot-demo
          image: {IMAGE}
          ports:
            - containerPort: 8080
---
#Service
apiVersion: v1
kind: Service
metadata:
  namespace: springboot-demo
  name: springboot-demo-service
  labels:
    app: springboot-demo
spec:
  selector:
    app: springboot-demo
  ports:
    - protocol: TCP
      port: 8080 #对集群内开放的端口
      targetPort: 8080 #容器暴露的端口
---
#Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: springboot-demo
  name: springboot-demo-ingress
  labels:
    app: springboot-demo
spec:
  rules:
    - host: springboot-demo.zl52074.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: springboot-demo-service
                port:
                  number: 8080
